name: Test ntfy
on: workflow_dispatch # Позволяет запустить вручную кнопкой

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Notification
        run: |
          curl -H "Title: Test Alert" \
               -H "Priority: high" \
               -H "Tags: white_check_mark" \
               -d "Проверка связи! Если ты это видишь, ntfy работает." \
               https://ntfy.sh/alertnesss
